#pragma once

#define SERVER_PORT 8080
#define SERVER_ADDRESS "127.0.0.1"
#define MAX_MESSAGE_SIZE 512

#define MAX_CLIENTS 10
#define MAX_EVENTS MAX_CLIENTS * 2
#define MAX_COMMAND_SIZE 20
#define MAX_MESSAGE_CONTENT (MAX_MESSAGE_SIZE - MAX_COMMAND_SIZE - 1)